name: tailwind-example
recipe: laravel
config:
  webroot: public
  via: nginx
  cache: redis
services:
  appserver:
    build:
      - composer install
  node:
    type: node
    build:
      - npm install
      - npm run dev
